// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_-I_tuZfM8z5zL2PqZrs7QLO13ERrWtA',
    appId: '1:130727325379:web:01581e8a9b5a3af506fc76',
    messagingSenderId: '130727325379',
    projectId: 'neu-info6350-f3e24',
    authDomain: 'neu-info6350-f3e24.firebaseapp.com',
    storageBucket: 'neu-info6350-f3e24.appspot.com',
    measurementId: 'G-KF7RB2WVCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA0fYAuW42KBoWN0sTJhu8dMRL5D_aSls',
    appId: '1:130727325379:android:37d6f6d034e40fda06fc76',
    messagingSenderId: '130727325379',
    projectId: 'neu-info6350-f3e24',
    storageBucket: 'neu-info6350-f3e24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8cQneg7OhaWyHg6yOcNKsZpMplGohu6g',
    appId: '1:130727325379:ios:93d15d06502bcd0406fc76',
    messagingSenderId: '130727325379',
    projectId: 'neu-info6350-f3e24',
    storageBucket: 'neu-info6350-f3e24.appspot.com',
    iosBundleId: 'com.example.bmiCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8cQneg7OhaWyHg6yOcNKsZpMplGohu6g',
    appId: '1:130727325379:ios:93d15d06502bcd0406fc76',
    messagingSenderId: '130727325379',
    projectId: 'neu-info6350-f3e24',
    storageBucket: 'neu-info6350-f3e24.appspot.com',
    iosBundleId: 'com.example.bmiCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_-I_tuZfM8z5zL2PqZrs7QLO13ERrWtA',
    appId: '1:130727325379:web:01581e8a9b5a3af506fc76',
    messagingSenderId: '130727325379',
    projectId: 'neu-info6350-f3e24',
    authDomain: 'neu-info6350-f3e24.firebaseapp.com',
    storageBucket: 'neu-info6350-f3e24.appspot.com',
    measurementId: 'G-KF7RB2WVCC',
  );
}
